### ISSUE TITLE
Code does not give plot related response and throws error at frontend

### ISSUE THREAD

**Issue by astro-siddhesh** [langchain-ai/langchain-benchmarks#11]
my code : 

import pandas as pd
import streamlit as st
from langchain.chat_models import ChatOpenAI
from langchain.agents.agent_toolkits import create_pandas_dataframe_agent
from langchain.agents.agent_types import AgentType
import matplotlib.pyplot as plt

df = pd.read_csv('/Users/siddheshphapale/Desktop/project/sqlcsv.csv')

llm = ChatOpenAI(openai_api_key= "s5" , temperature=0 ,max_tokens= 500 , verbose= False)
agent = create_pandas_dataframe_agent(llm, df, agent_type=AgentType.OPENAI_FUNCTIONS)

from langsmith import Client
client = Client()
def send_feedback(run_id, score):
    client.create_feedback(run_id, "user_score", score=score)

st.set_page_config(page_title='🦜🔗 <img width="720" alt="Screenshot 2023-09-30 at 8 03 24 PM" src="https://github.com/langchain-ai/langchain-benchmarks/assets/118797304/0ad741c7-e926-4b00-aca2-3b97a0bae9c1">
st.title('📊🔗')
st.info("")

query_text = st.text_input('Enter your question:', placeholder = 'region wise total net amt')
# Form input and query
result = None
with st.form('myform', clear_on_submit=True):
	submitted = st.form_submit_button('Submit')
	if submitted:
		with st.spinner('Calculating...'):
			response = agent({"input": query_text}, include_run_info=True)
			result = response["output"]
			run_id = response["__run"].run_id
if result is not None:
	st.info(result)
	col_blank, col_text, col1, col2 = st.columns([10, 2,1,1])
	with col_text:
		st.text("Feedback:")
	with col1:
		st.button("👍", on_click=send_feedback, args=(run_id, 1))
	with col2:
		st.button("👎", on_click=send_feedback, args=(run_id, 0))

**Comment by hinthornw** [comment]
@astro-siddhesh I think this may be meant for a different repo. Do you have a question bout the benchmarks?
