### ISSUE TITLE
Does LangChain-Benchmarks only support models from the model registry?

### ISSUE THREAD

**Issue by harpreetsahota204** [langchain-ai/langchain-benchmarks#159]
I'd like to run some benchmarks against models from Hugging Face. The tutorials seem tailored for models from the registry or OpenAI. 

Before I go down the rabbit hole and try to use it myself, I thought I'd see if it was possible or if anyone has done this before and has examples I can look at.

Thanks

**Comment by hinthornw** [comment]
Nope! The registry is a convenience wrapper, but you can run it on anything. Here's an example that's more manual: https://langchain-ai.github.io/langchain-benchmarks/notebooks/tool_usage/intro.html#custom-agent-factory

Or you can pass in a langchain LLM to the other agent "factories"
